module.exports = {
  FILTER_DRAFTS: 'FILTER_DRAFTS',
  RECEIVED_DRAFT: 'RECEIVED_DRAFT',
  RECEIVED_FEATURED_DRAFTS: 'RECEIVED_FEATURED_DRAFTS',
  CREATED_DRAFT: 'CREATED_DRAFT',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE'
}
